<?php

/**
 * PluginCategoriasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCategoriasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCategoriasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCategorias');
    }
}