<?php

/**
 * ProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Products');
    }
    
    public function getLuceneIndex()
    {
      ProjectConfiguration::registerZend();

      if (file_exists($index = $this->getLuceneIndexFile()))
      {
        return Zend_Search_Lucene::open($index);
      }
      else
      {
        return Zend_Search_Lucene::create($index);
      }
    }

    public function getLuceneIndexFile()
    {
      //return sfConfig::get('sf_data_dir').'/'.sfConfig::get('sf_environment').'.index';
    }
    
    public function getForLuceneQuery($query)
    {
      $hits = self::getLuceneIndex()->find($query);

      $pks = array();
      foreach ($hits as $hit)
      {
        $pks[] = $hit->pk;
      }

      if (empty($pks))
      {
        return array();
      }

      $q = $this->createQuery('p')
        ->whereIn('p.id', $pks)
        ->limit(20);

      $q = $this->addActiveJobsQuery($q);

      return $q->execute();
    }
    
    /*public function getCatName(){
        $q = Doctrine_Core::getTable('Products')
          ->createQuery('p')
          ->where('p.cat_id = ?', 'c.cat_id')
          ->innerJoin('Categories c')
          ->orderBy('c.id DESC');
        return $q->execute();
    }*/
    
    /*public function getProducts(Doctrine_Query $q = null){
        $q = Doctrine_Core::getTable('Products')->findAll();
        return $q;
    }*/
}