<?php

/**
 * BaseServicios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ser_icono
 * @property string $ser_link
 * @property string $ser_nombre
 * 
 * @method string    getSerIcono()   Returns the current record's "ser_icono" value
 * @method string    getSerLink()    Returns the current record's "ser_link" value
 * @method string    getSerNombre()  Returns the current record's "ser_nombre" value
 * @method Servicios setSerIcono()   Sets the current record's "ser_icono" value
 * @method Servicios setSerLink()    Sets the current record's "ser_link" value
 * @method Servicios setSerNombre()  Sets the current record's "ser_nombre" value
 * 
 * @package    portal-educacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicios');
        $this->hasColumn('ser_icono', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ser_link', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ser_nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}