<?php

/**
 * BaseRolesCategorias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rol_cat_id
 * @property integer $rol_group_id
 * @property Categorias $Categorias
 * @property sfGuardGroup $sfGuardGroup
 * 
 * @method integer         getRolCatId()     Returns the current record's "rol_cat_id" value
 * @method integer         getRolGroupId()   Returns the current record's "rol_group_id" value
 * @method Categorias      getCategorias()   Returns the current record's "Categorias" value
 * @method sfGuardGroup    getSfGuardGroup() Returns the current record's "sfGuardGroup" value
 * @method RolesCategorias setRolCatId()     Sets the current record's "rol_cat_id" value
 * @method RolesCategorias setRolGroupId()   Sets the current record's "rol_group_id" value
 * @method RolesCategorias setCategorias()   Sets the current record's "Categorias" value
 * @method RolesCategorias setSfGuardGroup() Sets the current record's "sfGuardGroup" value
 * 
 * @package    portal-educacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRolesCategorias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('roles_categorias');
        $this->hasColumn('rol_cat_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rol_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categorias', array(
             'local' => 'rol_cat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup', array(
             'local' => 'rol_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}