<?php

/**
 * BotonesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BotonesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BotonesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Botones');
    }
}