<?php

/**
 * RolesCategoriasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolesCategoriasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolesCategoriasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RolesCategorias');
    }
}