<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/10/02 09:43:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'criss',
  'name' => 'doctrine',
)),);
