<?php

/**
 * BaseRoles_categoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rol_user_id
 * @property integer $rol_cat_id
 * @property integer $rol_group_id
 * @property sfGuardUser $sfGuardUser
 * @property Categorias $Categorias
 * @property sfGuardGroup $sfGuardGroup
 * 
 * @method integer         getRolUserId()    Returns the current record's "rol_user_id" value
 * @method integer         getRolCatId()     Returns the current record's "rol_cat_id" value
 * @method integer         getRolGroupId()   Returns the current record's "rol_group_id" value
 * @method sfGuardUser     getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method Categorias      getCategorias()   Returns the current record's "Categorias" value
 * @method sfGuardGroup    getSfGuardGroup() Returns the current record's "sfGuardGroup" value
 * @method Roles_categoria setRolUserId()    Sets the current record's "rol_user_id" value
 * @method Roles_categoria setRolCatId()     Sets the current record's "rol_cat_id" value
 * @method Roles_categoria setRolGroupId()   Sets the current record's "rol_group_id" value
 * @method Roles_categoria setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * @method Roles_categoria setCategorias()   Sets the current record's "Categorias" value
 * @method Roles_categoria setSfGuardGroup() Sets the current record's "sfGuardGroup" value
 * 
 * @package    portal-educacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoles_categoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('roles_categoria');
        $this->hasColumn('rol_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rol_cat_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rol_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'rol_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Categorias', array(
             'local' => 'rol_cat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup', array(
             'local' => 'rol_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}