<?php

/**
 * BaseBotones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $btn_nombre
 * @property string $btn_link
 * @property string $btn_imagen
 * @property integer $btn_activo
 * @property integer $btn_cat_id
 * @property Categorias $Categorias
 * 
 * @method string     getBtnNombre()  Returns the current record's "btn_nombre" value
 * @method string     getBtnLink()    Returns the current record's "btn_link" value
 * @method string     getBtnImagen()  Returns the current record's "btn_imagen" value
 * @method integer    getBtnActivo()  Returns the current record's "btn_activo" value
 * @method integer    getBtnCatId()   Returns the current record's "btn_cat_id" value
 * @method Categorias getCategorias() Returns the current record's "Categorias" value
 * @method Botones    setBtnNombre()  Sets the current record's "btn_nombre" value
 * @method Botones    setBtnLink()    Sets the current record's "btn_link" value
 * @method Botones    setBtnImagen()  Sets the current record's "btn_imagen" value
 * @method Botones    setBtnActivo()  Sets the current record's "btn_activo" value
 * @method Botones    setBtnCatId()   Sets the current record's "btn_cat_id" value
 * @method Botones    setCategorias() Sets the current record's "Categorias" value
 * 
 * @package    portal-educacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBotones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('botones');
        $this->hasColumn('btn_nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('btn_link', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('btn_imagen', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('btn_activo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('btn_cat_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categorias', array(
             'local' => 'btn_cat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}