<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/10/02 11:45:10
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
