<?php

/**
 * RolesCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolesCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolesCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RolesCategoria');
    }
}