<?php

/**
 * Roles_categoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Roles_categoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Roles_categoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Roles_categoria');
    }
}