<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/21 15:40:40
sfConfig::add(array(
  'mod_sf_guard_group_enabled' => true,
  'mod_sf_guard_group_view_class' => 'sfPHP',
));
