<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/21 15:40:01
sfConfig::add(array(
  'mod_sf_guard_permission_enabled' => true,
  'mod_sf_guard_permission_view_class' => 'sfPHP',
));
