<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/12/15 15:52:44
sfConfig::add(array(
  'mod_sf_guard_permission_enabled' => true,
  'mod_sf_guard_permission_view_class' => 'sfPHP',
));
