<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/12/15 15:52:07
sfConfig::add(array(
  'mod_sf_guard_group_enabled' => true,
  'mod_sf_guard_group_view_class' => 'sfPHP',
));
