<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/12/14 15:22:37
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
