<?php

/**
 * BaseCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cat_name
 * @property Doctrine_Collection $prd_cat_name
 * 
 * @method string              getCatName()      Returns the current record's "cat_name" value
 * @method Doctrine_Collection getPrdCatName()   Returns the current record's "prd_cat_name" collection
 * @method Categories          setCatName()      Sets the current record's "cat_name" value
 * @method Categories          setPrdCatName()   Sets the current record's "prd_cat_name" collection
 * 
 * @package    repaso
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategories extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categories');
        $this->hasColumn('cat_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Products as prd_cat_name', array(
             'local' => 'id',
             'foreign' => 'cat_id'));
    }
}