<?php

/**
 * BaseProducts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $prd_slug
 * @property string $prd_name
 * @property string $prd_description
 * @property integer $prd_price
 * @property integer $cat_id
 * @property string $prd_created
 * @property string $prd_photo
 * @property Categories $Categories
 * 
 * @method string     getPrdSlug()         Returns the current record's "prd_slug" value
 * @method string     getPrdName()         Returns the current record's "prd_name" value
 * @method string     getPrdDescription()  Returns the current record's "prd_description" value
 * @method integer    getPrdPrice()        Returns the current record's "prd_price" value
 * @method integer    getCatId()           Returns the current record's "cat_id" value
 * @method string     getPrdCreated()      Returns the current record's "prd_created" value
 * @method string     getPrdPhoto()        Returns the current record's "prd_photo" value
 * @method Categories getCategories()      Returns the current record's "Categories" value
 * @method Products   setPrdSlug()         Sets the current record's "prd_slug" value
 * @method Products   setPrdName()         Sets the current record's "prd_name" value
 * @method Products   setPrdDescription()  Sets the current record's "prd_description" value
 * @method Products   setPrdPrice()        Sets the current record's "prd_price" value
 * @method Products   setCatId()           Sets the current record's "cat_id" value
 * @method Products   setPrdCreated()      Sets the current record's "prd_created" value
 * @method Products   setPrdPhoto()        Sets the current record's "prd_photo" value
 * @method Products   setCategories()      Sets the current record's "Categories" value
 * 
 * @package    repaso
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProducts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('products');
        $this->hasColumn('prd_slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('prd_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('prd_description', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
        $this->hasColumn('prd_price', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cat_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('prd_created', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('prd_photo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categories', array(
             'local' => 'cat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'prd_name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}