<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/10/24 09:30:12

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=catalogo',
  'username' => 'root',
  'password' => 'criss',
  'name' => 'doctrine',
)),);
