<?php

/**
 * TipoDeLoginTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoDeLoginTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoDeLoginTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoDeLogin');
    }
}