<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/11/14 16:07:51
$this->security = array (
  'home' => 
  array (
    'is_secure' => true,
    'credentials' => 'user',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
