<?php

/**
 * BaseTipoDeLogin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activo
 * 
 * @method integer     getActivo() Returns the current record's "activo" value
 * @method TipoDeLogin setActivo() Sets the current record's "activo" value
 * 
 * @package    portal-educacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoDeLogin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_de_login');
        $this->hasColumn('activo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}