<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/11/21 16:01:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=portal_educacion',
  'username' => 'root',
  'password' => 'criss',
  'name' => 'doctrine',
)),);
