<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/09/29 16:05:00
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
  'app_sf_guard_plugin_routes_register' => false,
));
