<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/09/29 16:05:03
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
);
